; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
board_build.ldscript = teensy41_mmb.ld
framework = arduino
build_flags = 
	-D USB_MIDI_AUDIO_SERIAL
	-D TEENSY_OPT_FASTER
	-I ../core/include
	-I .pio/libdeps/teensy41/ArduinoJson/src
	-I ../app-elements/lib/mi-elements
lib_extra_dirs =
	..
	../app-elements/lib
	../lib
lib_deps =
	core
	mi-elements
	mi-rings
	mi-plaits
	mi-clouds
	mi-tides
    mi-marbles
    msfa
    mi-warps
	stk
	bblanchon/ArduinoJson@^7.1.0
lib_ldf_mode = deep+
upload_protocol = teensy-gui
monitor_speed = 115200
