#pragma once
/**
 * @file WtVcoModule.h
 * @brief Wavetable oscillator (typeId `tp_mmb_wt_vco`, FW-AU-5): an
 *        `AudioSynthWaveform` driven by built-in single-cycle tables.
 *
 * @details
 * A bank of harmonically-rich single-cycle waveforms, selectable live with the
 * `bank` control.  Each table is generated by additive synthesis into a
 * per-instance 256-sample buffer and handed to `AudioSynthWaveform::
 * arbitraryWaveform()`.  Pitch tracking is identical to the plain VCO
 * (0 V = C4 = 261.626 Hz).
 *
 * Banks:
 * | idx | name    | recipe                                  |
 * |-----|---------|-----------------------------------------|
 * | 0   | Saw     | all harmonics, amplitude 1/n            |
 * | 1   | Square  | odd harmonics, amplitude 1/n            |
 * | 2   | Triangle| odd harmonics, amplitude 1/n², altsign  |
 * | 3   | Organ   | octave-spaced harmonics (1,2,4,8)       |
 * | 4   | Pulse25 | 25 % duty pulse (band-limited sum)      |
 * | 5   | Vocal   | formant-weighted harmonic stack         |
 *
 * Port map:
 * | Direction | portId | Domain | Stream / channel   |
 * |-----------|--------|--------|--------------------|
 * | input     | `voct` | Cv     | pitch (V/Oct)      |
 * | input     | `tune` | Cv     | aux V/Oct shift    |
 * | output    | `out`  | Audio  | `osc_`, channel 0  |
 *
 * Controls:
 * | controlId | type    | effect                            |
 * |-----------|---------|-----------------------------------|
 * | `bank`    | int32_t | Wavetable index (0 … 5)           |
 * | `coarse`  | float   | Semitone offset                   |
 * | `fine`    | float   | Cent offset                       |
 * | `level`   | float   | Output amplitude (0 … 1)          |
 */

#include "AudioModule.h"
#include "mb/runtime/Registry.h"
#include <Audio.h>
#include <cmath>
#include <cstdint>
#include <string_view>

namespace mmb_link {

/** @brief Wavetable oscillator with built-in additive banks. */
class WtVcoModule final : public AudioModule {
public:
    static constexpr const char* kTypeId = "tp_mmb_wt_vco";
    static constexpr int kTableLen = 256;
    static constexpr int kBanks    = 6;

    explicit WtVcoModule(std::string_view id)
        : AudioModule(kTypeId, id)
    {
        fillBank(bank_);
        osc_.arbitraryWaveform(table_, AUDIO_SAMPLE_RATE_EXACT * 0.5f);
        osc_.begin(WAVEFORM_ARBITRARY);
        osc_.amplitude(0.8f);
        recomputeHz();
    }

    AudioPort outputPort(std::string_view portId) const override {
        if (portId == "out")
            return { const_cast<AudioSynthWaveform*>(&osc_), 0, true };
        return {};
    }
    AudioPort inputPort(std::string_view /*portId*/) const override { return {}; }

    PortKind outputPortKind(std::string_view portId) const override {
        return (portId == "out") ? PortKind::Audio : PortKind::None;
    }
    PortKind inputPortKind(std::string_view portId) const override {
        if (portId == "voct" || portId == "tune") return PortKind::Cv;
        return PortKind::None;
    }
    void writeCvPort(std::string_view portId, float value) override {
        if      (portId == "voct") { voct_ = value; recomputeHz(); }
        else if (portId == "tune") { tune_ = value; recomputeHz(); }
    }

    void setControl(std::string_view controlId,
                    mb::runtime::ControlValue value) override {
        auto asFloat = [&](float fallback) -> float {
            if (auto* f = std::get_if<float>   (&value)) return *f;
            if (auto* i = std::get_if<int32_t> (&value)) return static_cast<float>(*i);
            return fallback;
        };
        auto asInt = [&](int32_t fallback) -> int32_t {
            if (auto* i = std::get_if<int32_t>(&value)) return *i;
            if (auto* f = std::get_if<float>  (&value)) return static_cast<int32_t>(*f);
            return fallback;
        };
        if (controlId == "bank") {
            int32_t b = asInt(0);
            if (b < 0) b = 0;
            if (b >= kBanks) b = kBanks - 1;
            if (b != bank_) {
                bank_ = b;
                fillBank(bank_);
                osc_.arbitraryWaveform(table_, AUDIO_SAMPLE_RATE_EXACT * 0.5f);
            }
        } else if (controlId == "coarse") {
            coarse_ = asFloat(0.0f); recomputeHz();
        } else if (controlId == "fine") {
            fine_ = asFloat(0.0f); recomputeHz();
        } else if (controlId == "level") {
            osc_.amplitude(asFloat(0.8f));
        }
    }

    /** @brief Register the wavetable-VCO factory.  Idempotent. */
    static void registerFactory() {
        auto& reg = mb::runtime::Registry::global();
        if (reg.has(kTypeId)) return;
        reg.register_(kTypeId,
            [](std::string_view id) -> std::unique_ptr<mb::runtime::Module> {
                return std::make_unique<WtVcoModule>(id);
            });
    }

private:
    void recomputeHz() {
        const float hz = 261.6256f
            * powf(2.0f, voct_ + tune_ + coarse_ / 12.0f + fine_ / 1200.0f);
        osc_.frequency(hz);
    }

    /** @brief Additive-synthesis fill of `table_` for the given bank index. */
    void fillBank(int bank) {
        float acc[kTableLen] = { 0.0f };
        const int maxH = 48;  // harmonic count (band-limited-ish)
        for (int n = 1; n <= maxH; ++n) {
            float amp = 0.0f;
            switch (bank) {
                case 0: amp = 1.0f / n; break;                              // saw
                case 1: amp = (n % 2) ? 1.0f / n : 0.0f; break;            // square
                case 2: amp = (n % 2) ? (((n / 2) % 2 ? -1.0f : 1.0f)
                                         / (n * n)) : 0.0f; break;          // triangle
                case 3: { int p = 1; bool oct = false;                      // organ
                          for (; p <= n; p <<= 1) if (p == n) { oct = true; break; }
                          amp = oct ? 1.0f / n : 0.0f; break; }
                case 4: amp = (2.0f / (n * static_cast<float>(M_PI)))       // 25% pulse
                              * sinf(n * static_cast<float>(M_PI) * 0.25f); break;
                case 5: {                                                   // vocal/formant
                          const float f = n / 6.0f;          // formant near 6th harm
                          amp = (1.0f / n) * expf(-(f - 1.0f) * (f - 1.0f) * 2.0f);
                          break; }
                default: amp = 1.0f / n; break;
            }
            if (amp == 0.0f) continue;
            for (int i = 0; i < kTableLen; ++i) {
                const float ph = (2.0f * static_cast<float>(M_PI) * n * i) / kTableLen;
                acc[i] += amp * sinf(ph);
            }
        }
        // Normalise to full int16 range.
        float peak = 1e-6f;
        for (int i = 0; i < kTableLen; ++i) {
            const float a = fabsf(acc[i]);
            if (a > peak) peak = a;
        }
        const float scale = 32767.0f / peak;
        for (int i = 0; i < kTableLen; ++i)
            table_[i] = static_cast<int16_t>(acc[i] * scale);
    }

    mutable AudioSynthWaveform osc_;
    int16_t table_[kTableLen] = { 0 };
    int     bank_   = 0;
    float   voct_   = 0.0f;
    float   tune_   = 0.0f;
    float   coarse_ = 0.0f;
    float   fine_   = 0.0f;
};

}  // namespace mmb_link
